# file with a bunch of snapshots
input_file: 
  format: fits
  filenames: 
    - '/data/test_out.fits'
# directory where output pictures would be stored
output_dir: /data/analysis'

# figure size in inches
figsize: [20, 11]

# description of plots layout in following format:
# - coords: [x, y, width, height]
#   params: 
#      attr: value
#   tasks:
#       - task 1
#       - task 2
#
# params should be given the same names as ones in matplotlib.pyplot (and proper values) as most of them are just passed along to it
plot_interval: 1

plots: 
  # Left coordinate plot
  - coords: [0, 0.35, 0.35, 0.6]
    params: 
      xlim: [-45, 45]
      ylim: [-40, 40]
      xlabel: 'z, kpc'
      ylabel: 'y, kpc'
      xticks: [0, 10]
      yticks: [0, 10]
    tasks:
      - name: ScatterTask
        args:
          x_expr: 'z'
          y_expr: 'y'
          x_unit: !q [1, kpc]
          y_unit: !q [1, kpc]
        slice: [0, 1000000]
        display: 
          is_density_plot: True
          resolution: 700
          extent: [-45, 45, -40, 40]
          channel: b
      - name: ScatterTask
        args:
          x_expr: 'z'
          y_expr: 'y'
          x_unit: !q [1, kpc]
          y_unit: !q [1, kpc]
        slice: [1000001, 1500002]
        display: 
          is_density_plot: True
          resolution: 700
          extent: [-45, 45, -40, 40]
          channel: r
      - name: ScatterTask
        args:
          x_expr: 'z'
          y_expr: 'y'
          x_unit: !q [1, kpc]
          y_unit: !q [1, kpc]
        slice: [0, 1]
        display: 
          linestyle: solid
          color: b
          marker: o
          markersize: 5
      - name: ScatterTask
        args:
          x_expr: 'z'
          y_expr: 'y'
          x_unit: !q [1, kpc]
          y_unit: !q [1, kpc]
        slice: [1000001, 1000002]
        display: 
          linestyle: solid
          color: b
          marker: o
          markersize: 5
      
  # Right coordinate plot
  - coords: [0.33, 0.35, 0.35, 0.6]
    params: 
      xlim: [-45, 45]
      ylim: [-40, 40]
      xlabel: 'x, kpc'
      yticks: []
      xticks: [0, 10]
    tasks:
      - name: ScatterTask
        args:
          x_expr: 'x'
          y_expr: 'y'
          x_unit: !q [1, kpc]
          y_unit: !q [1, kpc]
        slice: [0, 1000000]
        display: 
          is_density_plot: True
          resolution: 700
          extent: [-45, 45, -40, 40]
          channel: b
      - name: ScatterTask
        args:
          x_expr: 'x'
          y_expr: 'y'
          x_unit: !q [1, kpc]
          y_unit: !q [1, kpc]
        slice: [1000001, 1500002]
        display: 
          is_density_plot: True
          resolution: 700
          extent: [-45, 45, -40, 40]
          channel: r
      - name: ScatterTask
        args:
          x_expr: 'x'
          y_expr: 'y'
          x_unit: !q [1, kpc]
          y_unit: !q [1, kpc]
        slice: [0, 1]
        display: 
          linestyle: solid
          color: b
          marker: o
          markersize: 5
      - name: ScatterTask
        args:
          x_expr: 'x'
          y_expr: 'y'
          x_unit: !q [1, kpc]
          y_unit: !q [1, kpc]
        slice: [1000001, 1000002]
        display: 
          linestyle: solid
          color: b
          marker: o
          markersize: 5

  # Potential profile plot
  - coords: [0.72, 0.66, 0.14, 0.3]
    params: 
      xlim: [0, 50]
      ylim: [0, 3]
      xlabel: '$r$, kpc'
      ylabel: 'potential, $\frac{\varphi(r)}{\bar{\varphi}}$'
    tasks:
      - name: PotentialTask
        args: {}
        slice: [1000001, 1500002]
        display:
          linestyle: None
          color: r
          label: satellite
      - name: PotentialTask
        args: {}
        slice: [0, 1000001]
        display:
          linestyle: None
          color: b
          label: host
      - name: PotentialTask
        args: {}
        display:
          linestyle: None
          color: y
          label: all

  # Kinetic energy plot
  - coords: [0.72, 0.33, 0.14, 0.3]
    params:
      xlim: [0, 1000]
      ylim: [0, 3.e+52]
      xlabel: 'Time, Myr'
      ylabel: 'Keenetic energy, J'
      grid: True
    tasks:
      - name: TimeEvolutionTask
        args: 
          expr: 'm * (vx ** 2 + vy ** 2 + vz ** 2) / 2'
          function: 'sum'
          time_unit: !q [1, Myr]
          value_unit: !q [1, J]
        display: 
          linestyle: solid
          color: r

  # Separation plot
  - coords: [0, 0, 0.14, 0.3]
    params: 
      xlim: [0, 1000]
      ylim: [0, 150]
      xlabel: 'Time, Myr'
      ylabel: 'Separation, kpc'
      grid: True
    tasks: 
      - name: DistanceTask
        args: { start_id: 0, end_id: 1000001 }
        display: 
          linestyle: solid
          color: r

  # Velocity profile plot
  - coords: [0.18, 0, 0.32, 0.3]
    params: 
      xlim: [0, 15]
      ylim: [0, 400]
      xlabel: '$r$, kpc'
      ylabel: '$v$, km/s'
      grid: True
    tasks:
      - name: VelocityProfileTask
        args: {}
        slice: [0, 1000000]
        display:
          markersize: 0.5
          linestyle: None
          color: b
          label: host
      - name: VelocityProfileTask
        args: {}
        slice: [1000001, 1500002]
        display:
          markersize: 0.5
          linestyle: None
          color: r
          label: satellite
      - name: VelocityProfileTask
        args: {}
        display:
          markersize: 0.5
          linestyle: None
          color: y
          label: all

  # Mass profile plot
  - coords: [0.54, 0, 0.32, 0.3]
    params: 
      xlim: [0, 50]
      ylim: [0, 4.e+11]
      xlabel: '$r$, kpc'
      ylabel: '$M$, MSun'
      grid: True
    tasks:
      - name: MassProfileTask
        args: {}
        slice: [0, 1000000]
        display: 
          markersize: 0.5
          linestyle: None
          color: b
          label: host
      - name: MassProfileTask
        args: {}
        slice: [1000001, 1500002]
        display: 
          markersize: 0.5
          linestyle: None
          color: r
          label: satellite
      - name: MassProfileTask
        args: {}
        display: 
          markersize: 0.5
          linestyle: None
          color: y
          label: all