# you can use YAML anchors to substitute some values that repeat several times over the YAML.
# About YAML anchors: https://support.atlassian.com/bitbucket-cloud/docs/yaml-anchors/
host_slice: &host_slice
  - 0
  - 1000001
host_color: &host_clr b

sat_slice: &sat_slice
  - 1000001
  - 1500002
sat_color: &sat_clr r

all_color: &all_clr y

# file with a set of snapshots
input_file:
  format: fits
  filenames:
    - !env "{WORKING_DIR}/test_out.fits"

# You can specify filename where JSON logs would be saved
logging:
  filename: !env "{WORKING_DIR}/test_json_log.txt"
  datefmt: "%Y-%m-%d %H:%M:%S"

# visualizer service configuration. It specifies list of panels
visualizer:
  output_dir: !env "{WORKING_DIR}/analysis"
  title: "Time: {time:07.01f} Myr"
  figsize: [20, 11]
  pic_filename: "img-{i:03d}.png"
  panels:
    - id: zy_plane
      coords: [0, 0.35, 0.35, 0.6]
      params:
        xlim: [-45, 45]
        ylim: [-40, 40]
        xlabel: "z, kpc"
        ylabel: "y, kpc"
        xticks: [0, 10]
        yticks: [0, 10]
    - id: xy_plane
      coords: [0.33, 0.35, 0.35, 0.6]
      params:
        xlim: [-45, 45]
        ylim: [-40, 40]
        xlabel: "x, kpc"
        yticks: []
        xticks: [0, 10]
    - id: potential_dist_plane
      coords: [0.72, 0.66, 0.14, 0.3]
      params:
        xlim: [0, 50]
        ylim: [0, 3]
        xlabel: "$r$, kpc"
        ylabel: "Potential, portion of the average"
        grid: True
    - id: bound_mass_evolution_plane
      coords: [0.72, 0.33, 0.14, 0.3]
      params:
        xlim: [0, 10000]
        ylim: [0, 3.e+11]
        xlabel: "Time, Myr"
        ylabel: "Bound mass, MSun"
        grid: True
    - id: separation_evolution_panel
      coords: [0, 0, 0.14, 0.3]
      params:
        xlim: [0, 10000]
        ylim: [0, 150]
        xlabel: "Time, Myr"
        ylabel: "Separation, kpc"
        grid: True
    - id: velocity_profile_panel
      coords: [0.18, 0, 0.32, 0.3]
      params:
        xlim: [0, 15]
        ylim: [0, 400]
        xlabel: "$r$, kpc"
        ylabel: "$v$, km/s"
        grid: True
    - id: density_profile_panel
      coords: [0.54, 0, 0.32, 0.3]
      params:
        xlim: [0, 50]
        ylim: [0, 4.e+8]
        xlabel: "$r$, kpc"
        ylabel: '$\rho$, MSun / kpc ** 3'
        grid: True

# list of tasks. Each one describes arguments to its constructor, slice it operates on and list of actions.
tasks:
  - name: ScatterTask
    args:
      x_expr: "z"
      y_expr: "y"
      x_unit: !q [1, kpc]
      y_unit: !q [1, kpc]
    actions_before:
      - type: slice
        part: *host_slice
    actions_after:
      - type: visualizer
        id: zy_plane
        is_density_plot: True
        resolution: 700
        extent: [-45, 45, -40, 40]
        channel: *host_clr
  - name: ScatterTask
    args:
      x_expr: "z"
      y_expr: "y"
      x_unit: !q [1, kpc]
      y_unit: !q [1, kpc]
    actions_before:
      - type: slice
        part: *sat_slice
    actions_after:
      - type: visualizer
        id: zy_plane
        is_density_plot: True
        resolution: 700
        extent: [-45, 45, -40, 40]
        channel: *sat_clr
  - name: ScatterTask
    args:
      x_expr: "z"
      y_expr: "y"
      x_unit: !q [1, kpc]
      y_unit: !q [1, kpc]
    actions_before:
      - type: slice
        part: [0, 1]
    actions_after:
      - type: visualizer
        id: zy_plane
        linestyle: solid
        color: *host_clr
        marker: o
        markersize: 5
  - name: ScatterTask
    args:
      x_expr: "z"
      y_expr: "y"
      x_unit: !q [1, kpc]
      y_unit: !q [1, kpc]
    actions_before:
      - type: slice
        part: [1000001, 1000002]
    actions_after:
      - type: visualizer
        id: zy_plane
        linestyle: solid
        color: *sat_clr
        marker: o
        markersize: 5

  - name: ScatterTask
    args:
      x_expr: "x"
      y_expr: "y"
      x_unit: !q [1, kpc]
      y_unit: !q [1, kpc]
    actions_before:
      - type: slice
        part: *host_slice
    actions_after:
      - type: visualizer
        id: xy_plane
        is_density_plot: True
        resolution: 700
        extent: [-45, 45, -40, 40]
        channel: *host_clr
  - name: ScatterTask
    args:
      x_expr: "x"
      y_expr: "y"
      x_unit: !q [1, kpc]
      y_unit: !q [1, kpc]
    actions_before:
      - type: slice
        part: *sat_slice
    actions_after:
      - type: visualizer
        id: xy_plane
        is_density_plot: True
        resolution: 700
        extent: [-45, 45, -40, 40]
        channel: *sat_clr
  - name: ScatterTask
    args:
      x_expr: "x"
      y_expr: "y"
      x_unit: !q [1, kpc]
      y_unit: !q [1, kpc]
    actions_before:
      - type: slice
        part: [0, 1]
    actions_after:
      - type: visualizer
        id: xy_plane
        linestyle: solid
        color: *host_clr
        marker: o
        markersize: 5
  - name: ScatterTask
    args:
      x_expr: "x"
      y_expr: "y"
      x_unit: !q [1, kpc]
      y_unit: !q [1, kpc]
    actions_before:
      - type: slice
        part: [1000001, 1000002]
    actions_after:
      - type: visualizer
        id: xy_plane
        linestyle: solid
        color: *sat_clr
        marker: o
        markersize: 5

  - name: PotentialTask
    args:
      center_type: potential
    actions_before:
      - type: slice
        part: *host_slice
    actions_after:
      - type: visualizer
        id: potential_dist_plane
        linestyle: None
        color: *host_clr
        label: host
  - name: PotentialTask
    args:
      center_type: potential
    actions_before:
      - type: slice
        part: *sat_slice
    actions_after:
      - type: visualizer
        id: potential_dist_plane
        linestyle: None
        color: *sat_clr
        label: satellite
  - name: PotentialTask
    args:
      center_type: potential
    actions_after:
      - type: visualizer
        id: potential_dist_plane
        linestyle: None
        color: *all_clr
        label: all

  - name: BoundMassTask
    args:
      number_of_iterations: 5
    actions_before:
      - type: slice
        part: *sat_slice
    actions_after:
      - type: visualizer
        id: bound_mass_evolution_plane
        linestyle: solid
        color: r
      - type: logging
        print_last: True
        id: bound_mass_data

  - name: DistanceTask
    args:
      start_id: 0
      relative_to: 1000001
    actions_after:
      - type: visualizer
        id: separation_evolution_panel
        linestyle: solid
        color: r

  - name: VelocityProfileTask
    args:
      center_type: potential
    actions_before:
      - type: slice
        part: *host_slice
    actions_after:
      - type: visualizer
        id: velocity_profile_panel
        markersize: 0.5
        linestyle: None
        color: *host_clr
        label: host
  - name: VelocityProfileTask
    args:
      center_type: potential
    actions_before:
      - type: slice
        part: *sat_slice
    actions_after:
      - type: visualizer
        id: velocity_profile_panel
        markersize: 0.5
        linestyle: None
        color: *sat_clr
        label: satellite
  - name: VelocityProfileTask
    args:
      center_type: potential
    actions_after:
      - type: visualizer
        id: velocity_profile_panel
        markersize: 0.5
        linestyle: None
        color: *all_clr
        label: all

  - name: DensityProfileTask
    args:
      center_type: potential
    actions_before:
      - type: slice
        part: *host_slice
    actions_after:
      - type: visualizer
        id: density_profile_panel
        markersize: 0.5
        linestyle: None
        color: *host_clr
        label: host
  - name: DensityProfileTask
    args:
      center_type: potential
    actions_before:
      - type: slice
        part: *sat_slice
    actions_after:
      - type: visualizer
        id: density_profile_panel
        markersize: 0.5
        linestyle: None
        color: *sat_clr
        label: satellite
  - name: DensityProfileTask
    args:
      center_type: potential
    actions_after:
      - type: visualizer
        id: density_profile_panel
        markersize: 0.5
        linestyle: None
        color: *all_clr
        label: all
