# output model would be written in this file
output_file: !env "{WORKING_DIR}/test.fits"
# what to do if output file already exists
overwrite: True

# You can specify list of logging handlers
logging:
  level: debug
  filename: !env "{WORKING_DIR}/test_json_log.txt"

# list of objects; they can be either read from csv files or given directly using masses and positions.
objects:
  # host black hole
  - type: body
    args:
      mass: !q [4.e+8, MSun]
    position: !q [[0, 0, 0], kpc]
    velocity: !q [[0, 0, 0], kms]
  # host galaxy
  - type: csv
    args:
      delimiter: " "
      path: !env "{DATA_DIR}/host.csv"
    position: !q [[0, 0, 0], kpc]
    velocity: !q [[0, 0, 0], kms]
  # satellite black hole
  - type: body
    args:
      mass: !q [1.e+8, MSun]
    position: !q [[20, 0, 0], kpc]
    velocity: !q [[0, 100, 0], kms]
  # satellite galaxy
  - type: csv
    args:
      delimiter: " "
      path: !env "{DATA_DIR}/sat.csv"
    position: !q [[20, 0, 0], kpc]
    velocity: !q [[0, 100, 0], kms]
