# output model would be written in this file
output_file: '/home/user/data/test.fits'

# list of objects; they can be either read from csv files or given directly using masses and positions.
objects: 
  # host black hole
  - type: 'body'
    mass: !q [4.e+8, MSun]
    position: !q [[0, 0, 0], kpc]
    velocity: !q [[0, 0, 0], kms]
  # host galaxy
  - type: 'csv'
    delimeter: ' '
    path: '/home/user/data/host.txt'
    position: !q [[0, 0, 0], kpc]
    velocity: !q [[0, 0, 0], kms]
  # satellite black hole
  - type: 'body'
    mass: !q [1.e+8, MSun]
    position: !q [[20, 0, 0], kpc]
    velocity: !q [[0, 100, 0], kpc]
  # satellite galaxy
  - type: 'csv'
    delimeter: ' '
    path: '/home/user/data/sat.txt'
    position: !q [[20, 0, 0], kpc]
    velocity: !q [[0, 100, 0], kpc]
