name: Building
on:
  - push

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest
    container: "kraysent/omtool:latest"
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Build pip package
        run: |
          python3  -m pip install . --upgrade
          python3 setup.py sdist
      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dist-folder
          path: dist/*
