name: Linting
on:
  - push

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: omtool
          python-version: "3.10"
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run isort
        run: make check-isort
      - name: Run black
        run: make check-black
      - name: Install core project deps
        run: |
          sudo apt-get install build-essential gfortran python3-dev \
          libopenmpi-dev openmpi-bin \
          libgsl-dev cmake libfftw3-3 libfftw3-dev \
          libgmp3-dev libmpfr6 libmpfr-dev \
          libhdf5-serial-dev hdf5-tools \
          libblas-dev liblapack-dev git
          python3 -m pip install -r requirements.txt
          git clone https://github.com/GalacticDynamics-Oxford/pyfalcon.git
          cd pyfalcon && python3 setup.py install
      - name: Run mypy
        run: |
          rm -rf pyfalcon
          make check-mypy
