name: Linting
on:
  - push

jobs:
  lint:
    runs-on: ubuntu-latest
    container: "kraysent/omtool:latest"
    steps:
      - name: Install check deps
        run: python3 -m pip install types-pyyaml isort mypy black
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run isort
        run: make check-isort
      - name: Run black
        run: make check-black
      - name: Run mypy
        run: make check-mypy
