name: Statistics
on:
  - push

jobs:
  statistics:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Python files
        run: find . -name '*.py' | xargs wc -l
      - name: YAML files
        run: find . -name '*.yaml' | xargs wc -l
      - name: JSON files
        run: find . -name '*.json' | xargs wc -l
      - name: Project tree
        run: tree